services:

  postgres:
    image: postgres:16-alpine
    container_name: shipment-service
    restart: always
    env_file:
      - .env
    volumes:
      - shipment-service_data:/var/lib/postgresql/data
      - ./init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql:ro
    networks:
      - shipments_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8889:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - shipments_network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP default port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shipments_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - shipments_network

  shipments:
    build:
      context: .
      target: dev
    container_name: shipments
    depends_on:
      - rabbitmq
      - postgres
      - mailhog
    init: true
    ports:
      - "5050:3000"
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
    env_file:
      - .env
    command: pnpm start:dev
    networks:
      - shipments_network

volumes:
  api_node_modules:
  shipment-service_data:
  pgadmin_data:
  rabbitmq_data:

networks:
  shipments_network:
    external: true
